language: ruby
sudo: false
gemfile: nubis/travis/Gemfile
cache:
  bundler: true
  directories:
  - "${HOME}/bin"
  - nubis/librarian-puppet
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
script:
- nubis/travis/run-checks
notifications:
  slack:
    secure: hCKjKQ2vZHPC5Q+Bz2WtjCAVmBxrAu37LUKRHX/h9Hfg8mZlZPRszwYiIUXCTXNDm9wEHiiwt8N6Ne3Fwyf+yn3VheRyEdUIPadPmubUT24EWx0BLkmCR+5ttMqzCjHg7DGYcGMc2QeLPIQeLOkGRHfz4jynngzU/Ds6OqLz2lw=
